### ISSUE TITLE
GRUPTREE

### ISSUE THREAD

**Issue by pgdr** [equinor/sunbeam#14]
We should be able to interact with _multi-level group control_ as specified via the `GRUPTREE` keyword (example from The Manual is attached)
```
GRUPTREE
--child parent
GR-A1   PLAT-A /
GR-A2   PLAT-A /
GR-B1   PLAT-B /
GR-B2   PLAT-B /
SAT-B   PLAT-B /
GR-S1   SAT-B  /
GR-S2   SAT-B  /
/
```

**Comment by pgdr** [comment]
should be able to get _pressure different nodes_ and _volume rate for g/o/w

**Comment by markusdregi** [comment]
The development of Sunbeam stopped a long time back. The development of the Python bindings are continued in [opm-common](https://github.com/OPM/opm-common) and our recommendation is to use these. Closing all issues.
