### ISSUE TITLE
Access PVT properties

### ISSUE THREAD

**Issue by pgdr** [equinor/sunbeam#15]
Read `PVTO` and `PVTG` tables; mainly to verify that PVT tables are physically consistent

Also for `VFP`?

**Comment by pgdr** [comment]
#29 initiates the work towards supporting this.

```python
>>> es = sunbeam.parse('NORNE_ATW2013.DATA')
>>> f = es.table['SWOF', 'KROW']
>>> f(0.2)
0.43286
>>> f(0.8)
0.00149
```

**Comment by pgdr** [comment]
From the `sunbeam/examples` folder there is a `swofplot` which files like this:
![img1](https://cloud.githubusercontent.com/assets/17569537/23071950/5a1e1a1e-f530-11e6-8555-ce95ae21eb2a.png)
![img2](https://cloud.githubusercontent.com/assets/17569537/23071951/5a3cc98c-f530-11e6-818d-21dc5c551501.png)

**Comment by joakim-hove** [comment]
:smile:

**Comment by joakim-hove** [comment]
Unfortunately not for VFP, they are a *completely* different beast. Uncertain of how complete that internalisation is.

**Comment by berland** [comment]
https://wiki.statoil.no/wiki/index.php/ResScript:Python:Scripts:vfp2csv.py and https://wiki.statoil.no/wiki/index.php/ResScript:Python:Scripts:pvt2csv are two existing implementation. 

No known bugs, but the PVT parsing in these are most likely not covering all corner cases.

**Comment by markusdregi** [comment]
The development of Sunbeam stopped a long time back. The development of the Python bindings are continued in [opm-common](https://github.com/OPM/opm-common) and our recommendation is to use these. Closing all issues.
