### ISSUE TITLE
Create schedule file - application

### ISSUE THREAD

**Issue by joakim-hove** [equinor/sunbeam#68]
This is my recollection of a tool for building up a SCHEDULE file which Håvard would like.

The tool is based on merging fragments of schedule files based on date.

**Comment by berland** [comment]
Internal (on resscrript) prototype available, named _sunsch_

**Comment by markusdregi** [comment]
The development of Sunbeam stopped a long time back. The development of the Python bindings are continued in [opm-common](https://github.com/OPM/opm-common) and our recommendation is to use these. Closing all issues.
