### ISSUE TITLE
Timestep offset

### ISSUE THREAD

**Issue by ReedOnly** [equinor/sunbeam#73]
When comparing timesteps from libecl module `EclSum.get_dates()` with sunbeam `schedule.timesteps` sunbeam timesteps appear to be off by 1 hour for some but not all timesteps. See example below:

```
a=ecl.get_dates(report_only=True)
b=sch.timesteps

for i in range(len(a)):
    print (a[i]==b[i] , str(a[i]) , ' : ' , str(b[i]))
  
(True, '1997-11-06 00:00:00', ' : ', '1997-11-06 00:00:00')
(True, '1997-11-14 00:00:00', ' : ', '1997-11-14 00:00:00')
(True, '1997-12-01 00:00:00', ' : ', '1997-12-01 00:00:00')
(True, '1997-12-17 00:00:00', ' : ', '1997-12-17 00:00:00')
(True, '1998-01-01 00:00:00', ' : ', '1998-01-01 00:00:00')
(True, '1998-02-01 00:00:00', ' : ', '1998-02-01 00:00:00')
(True, '1998-03-01 00:00:00', ' : ', '1998-03-01 00:00:00')
(True, '1998-03-29 00:00:00', ' : ', '1998-03-29 00:00:00')
(False, '1998-03-30 00:00:00', ' : ', '1998-03-30 01:00:00')
(False, '1998-04-01 00:00:00', ' : ', '1998-04-01 01:00:00')
(False, '1998-04-23 00:00:00', ' : ', '1998-04-23 01:00:00')
(False, '1998-05-01 00:00:00', ' : ', '1998-05-01 01:00:00')
(False, '1998-05-26 00:00:00', ' : ', '1998-05-26 01:00:00')
(False, '1998-05-27 00:00:00', ' : ', '1998-05-27 01:00:00')
```
This is for the norne case from [opm-data](https://github.com/OPM/opm-data/tree/master/norne) where it can be seen that some of the sunbeam timesteps are shifted one hour ahead of the corresponding Eclipse summaries.

**Comment by joakim-hove** [comment]
One hour - are we talking daylight savings time?

**Comment by joakim-hove** [comment]
Or maybe we have done something wrong with a TSTEP?

**Comment by anders-kiaer** [comment]
+1 for DST related issue. Daylight saving time in Norway in 1998 started on `1998-03-29 02:00:00`.

**Comment by markusdregi** [comment]
The development of Sunbeam stopped a long time back. The development of the Python bindings are continued in [opm-common](https://github.com/OPM/opm-common) and our recommendation is to use these. Closing all issues.
