### ISSUE TITLE
TimeVector initialiation or merge with another TimeVector

### ISSUE THREAD

**Issue by berland** [equinor/sunbeam#78]
The TimeVector.load() function should be able to load from an existing TimeVector object, effectively merging the two vectors. 

Keywords merged  onto the same date should have the order preserved from the load() statements.

**Comment by joakim-hove** [comment]
Or maybe a `TimeVector.merge()` method? 

> .... order preserved from the load() statements.

Ehhh no; that sounds ugly .... when doing:

```
tv1.merge(tv2)
```
we should have well defined ordering of tv1 and tv2  - indpendent of the load ordering?!

**Comment by joakim-hove** [comment]
OK @berland: Please prioritize: #77 or #78?

**Comment by berland** [comment]
#81 has higher priority than these. And #77 higher than #78.

The order preservation I specified was within each DATE. The overall order is well defined, as it is the dates, independent of load order.

`TimeVector.merge()` is ok!

**Comment by markusdregi** [comment]
The development of Sunbeam stopped a long time back. The development of the Python bindings are continued in [opm-common](https://github.com/OPM/opm-common) and our recommendation is to use these. Closing all issues.
