### ISSUE TITLE
not able to build sunbeam in Mac

### ISSUE THREAD

**Issue by miroine** [equinor/sunbeam#96]
Hei I am trying to install sunbeam on Mac .. but getting some issues to build it ... any thoughts on how I can solve the issue 
this is the error logs
miroine@Merouanes-MacBook-Air build % cmake ..
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_C99
-- Performing Test HAVE_C99 - Success
-- Found C99: -std=c99  
-- Checking to see if CXX compiler accepts flag -std=c++14
-- Checking to see if CXX compiler accepts flag -std=c++14 - yes
-- Performing Test HAVE_FINAL
-- Performing Test HAVE_FINAL - Success
-- Performing Test HAVE_TYPE_TRAITS
-- Performing Test HAVE_TYPE_TRAITS - Success
-- Performing Test HAVE_SHARED_PTR
-- Performing Test HAVE_SHARED_PTR - Success
-- Performing Test HAVE_UNIQUE_PTR
-- Performing Test HAVE_UNIQUE_PTR - Success
-- Performing Test HAVE_NULLPTR
-- Performing Test HAVE_NULLPTR - Success
-- Performing Test HAVE_CONSTEXPR
-- Performing Test HAVE_CONSTEXPR - Success
-- Performing Test HAVE_ARRAY
-- Performing Test HAVE_ARRAY - Success
-- Performing Test HAVE_INTEGRAL_CONSTANT
-- Performing Test HAVE_INTEGRAL_CONSTANT - Success
-- Looking for C++ include tuple
-- Looking for C++ include tuple - found
-- Looking for C++ include tr1/tuple
-- Looking for C++ include tr1/tuple - not found
-- Performing Test HAVE_ATTRIBUTE_ALWAYS_INLINE
-- Performing Test HAVE_ATTRIBUTE_ALWAYS_INLINE - Success
-- Performing Test HAS_ATTRIBUTE_UNUSED
-- Performing Test HAS_ATTRIBUTE_UNUSED - Success
-- Performing Test HAS_ATTRIBUTE_DEPRECATED
-- Performing Test HAS_ATTRIBUTE_DEPRECATED - Success
-- Performing Test HAS_ATTRIBUTE_DEPRECATED_MSG
-- Performing Test HAS_ATTRIBUTE_DEPRECATED_MSG - Success
-- Performing Test HAVE_STATIC_ASSERT
-- Performing Test HAVE_STATIC_ASSERT - Success
-- Performing Test HAVE_AUTO
-- Performing Test HAVE_AUTO - Success
-- Performing Test HAVE_VARIADIC_TEMPLATES
-- Performing Test HAVE_VARIADIC_TEMPLATES - Success
-- Performing Test HAVE_VARIADIC_CONSTRUCTOR_SFINAE
-- Performing Test HAVE_VARIADIC_CONSTRUCTOR_SFINAE - Success
-- Performing Test HAVE_RVALUE_REFERENCES
-- Performing Test HAVE_RVALUE_REFERENCES - Success
-- Looking for C++ include tr1/type_traits
-- Looking for C++ include tr1/type_traits - not found
CMake Warning at /usr/local/lib/cmake/boost_system-1.71.0/libboost_system-variant-shared.cmake:59 (message):
  Target Boost::system already has an imported location
  '/usr/local/lib/libboost_system-mt.dylib', which will be overwritten with
  '/usr/local/lib/libboost_system.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_system-1.71.0/boost_system-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  /usr/local/share/opm/cmake/Modules/OpmFind.cmake:156 (find_package)
  /usr/local/share/opm/cmake/Modules/OpmPackage.cmake:172 (find_and_append_package_to)
  /usr/local/share/opm/cmake/Modules/opm-common-prereqs.cmake:30 (find_package_deps)
  /usr/local/share/cmake/opm-common/opm-common-config.cmake:116 (include)
  CMakeLists.txt:7 (find_package)

CMake Warning at /usr/local/lib/cmake/boost_filesystem-1.71.0/libboost_filesystem-variant-shared.cmake:59 (message):
  Target Boost::filesystem already has an imported location
  '/usr/local/lib/libboost_filesystem-mt.dylib', which will be overwritten
  with '/usr/local/lib/libboost_filesystem.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_filesystem-1.71.0/boost_filesystem-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  /usr/local/share/opm/cmake/Modules/OpmFind.cmake:156 (find_package)
  /usr/local/share/opm/cmake/Modules/OpmPackage.cmake:172 (find_and_append_package_to)
  /usr/local/share/opm/cmake/Modules/opm-common-prereqs.cmake:30 (find_package_deps)
  /usr/local/share/cmake/opm-common/opm-common-config.cmake:116 (include)
  CMakeLists.txt:7 (find_package)

CMake Warning at /usr/local/lib/cmake/boost_unit_test_framework-1.71.0/libboost_unit_test_framework-variant-shared.cmake:59 (message):
  Target Boost::unit_test_framework already has an imported location
  '/usr/local/lib/libboost_unit_test_framework-mt.dylib', which will be
  overwritten with '/usr/local/lib/libboost_unit_test_framework.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_unit_test_framework-1.71.0/boost_unit_test_framework-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  /usr/local/share/opm/cmake/Modules/OpmFind.cmake:156 (find_package)
  /usr/local/share/opm/cmake/Modules/OpmPackage.cmake:172 (find_and_append_package_to)
  /usr/local/share/opm/cmake/Modules/opm-common-prereqs.cmake:30 (find_package_deps)
  /usr/local/share/cmake/opm-common/opm-common-config.cmake:116 (include)
  CMakeLists.txt:7 (find_package)

CMake Warning at /usr/local/lib/cmake/boost_regex-1.71.0/libboost_regex-variant-shared.cmake:59 (message):
  Target Boost::regex already has an imported location
  '/usr/local/lib/libboost_regex-mt.dylib', which will be overwritten with
  '/usr/local/lib/libboost_regex.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_regex-1.71.0/boost_regex-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  /usr/local/share/opm/cmake/Modules/OpmFind.cmake:156 (find_package)
  /usr/local/share/opm/cmake/Modules/OpmPackage.cmake:172 (find_and_append_package_to)
  /usr/local/share/opm/cmake/Modules/opm-common-prereqs.cmake:30 (find_package_deps)
  /usr/local/share/cmake/opm-common/opm-common-config.cmake:116 (include)
  CMakeLists.txt:7 (find_package)

-- Found Boost: /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.44.0") found components:  system filesystem unit_test_framework regex 
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.16") 
-- Found PythonLibs: /usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
-- pybind11 v2.4.dev4
CMake Error at python/CMakeLists.txt:1 (include):
  include could not find load file:

    FindPythonModule

CMake Error at python/CMakeLists.txt:2 (include):
  include could not find load file:

    PythonPackage

CMake Error at python/CMakeLists.txt:4 (python_module):
  Unknown CMake command "python_module".

-- Configuring incomplete, errors occurred!
See also "/Users/miroine/project_developments/repos/sunbeam/build/CMakeFiles/CMakeOutput.log".
See also "/Users/miroine/project_developments/repos/sunbeam/build/CMakeFiles/CMakeError.log".

**Comment by joakim-hove** [comment]
The development of Python wrappers fir opm-parser continues here: github.com/opm/opm-common. Feel free to ask there.

**Comment by miroine** [comment]
ok ... opm-common is building up correctly in mac but I need sunbeam module as it s used in ecl2df .... any idea how to get it ?

**Comment by miroine** [comment]
new errors now when I am trying to install
/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/include/python2.7/stringobject.h:173:5: warning: 
      'register' storage class specifier is deprecated and incompatible with
      C++17 [-Wdeprecated-register]
    register PyObject *obj,     /* string or Unicode object */
    ^~~~~~~~~
/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/include/python2.7/stringobject.h:174:5: warning: 
      'register' storage class specifier is deprecated and incompatible with
      C++17 [-Wdeprecated-register]
    register char **s,          /* pointer to buffer variable */
    ^~~~~~~~~
/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/include/python2.7/stringobject.h:175:5: warning: 
      'register' storage class specifier is deprecated and incompatible with
      C++17 [-Wdeprecated-register]
    register Py_ssize_t *len    /* pointer to length variable or NULL
    ^~~~~~~~~
/Users/miroine/project_developments/repos/sunbeam/sunbeam/eclipse_state.cpp:11:50: error: 
      no member named 'nncdata' in 'Opm::NNC'
        for( const auto& x : state.getInputNNC().nncdata() )
                             ~~~~~~~~~~~~~~~~~~~ ^
/Users/miroine/project_developments/repos/sunbeam/sunbeam/eclipse_state.cpp:92:48: error: 
      no member named 'get3DProperties' in 'Opm::EclipseState'
        .def( "_props",         &EclipseState::get3DProperties, ref_internal)
                                 ~~~~~~~~~~~~~~^
7 warnings and 2 errors generated.
make[2]: *** [sunbeam/CMakeFiles/libsunbeam.dir/eclipse_state.cpp.o] Error 1
make[1]: *** [sunbeam/CMakeFiles/libsunbeam.dir/all] Error 2
make: *** [all] Error 2

**Comment by anders-kiaer** [comment]
I think @berland has ported `ecl2df` from `sunbeam` to `opm.io` in this **unmerged** PR: https://github.com/equinor/ecl2df/pull/85. Is installing that "version" of `ecl2df` an alternative as for now @miroine?

The reason https://github.com/equinor/ecl2df/pull/85 has not been merged yet is according to @berland that Travis in that PR fails 🔴 on compiling `master` of `opm-common`. I.e. there are probably some fixes/changes needed in `.travis.yml` before `opm-common` compiles on Travis, and the `sunbeam → opm.io` port PR gets merged.

**Comment by ertomatic** [comment]
As @joakim-hove pointed out, the Python bindings have been moved to the opm-common project. Sunbeam will be officially discounted and archived as soon as ecl2df is ported. I would recommend the approach of @anders-kiaer as that might offer some useful testing for @berland. 

If it does not float your boat for some reason, you can do as we currently do in Komodo; namely build an older version of opm-common that sunbeam is compatible with. We use “ release/sunbeam/2019.02”, so that should work together with Sunbeam. But, as you can see, it is already a year old...

**Comment by markusdregi** [comment]
As @joakim-hove pointed out, the Python bindings have been moved to the opm-common project. Sunbeam will be officially discounted and archived as soon as ecl2df is ported. I would recommend the approach of @anders-kiaer as that might offer some useful testing for @berland. 

If it does not float your boat for some reason, you can do as we currently do in Komodo; namely build an older version of opm-common that sunbeam is compatible with. We use “ release/sunbeam/2019.02”, so that should work together with Sunbeam. But, as you can see, it is already a year old...
